### PR TITLE
Added Blog Entry-Google Bigtable

### PR DESCRIPTION
**Pull request by anukritijha246**
#### Type of Change:

- [ ] Code
- [x] Blog
- [ ] Resources

#### Description

Fixes #ISSUE_NUMBER_HERE

### CODE REVIEW

**Comment by czgdp1807** [comment]
Thanks for the PR.
I think you have merged master branch of your fork instead of the master of main repo.
Try the following,
```
git checkout master
git remote get-url origin
https://github.com/codezonediitj/codezonediitj.github.io/
git pull origin master
```
That should remove the blog entry of chromium. If you are unable to do it, let me know.

**Comment by anukritijha246** [comment]
I don't have write access on the original repo, can only work through fork,
which has blog entry for chromium.

**Comment by czgdp1807** [comment]
> I don't have write access on the original repo

IMO, `git pull` doesn't require write access to the main repo. You can `git push` to your fork after pulling the changes from the main repo in your `master` branch.

**Comment by anukritijha246** [comment]
I did pull the changes from the main repo in my master branch. Anyways, I deleted the chromium blog from my branch. I hope the pr can be merged now.😶😶

**Comment by czgdp1807** [comment]
Please enable the option "Allow edit from maintainers". See the right side menu for locating the option.

**Comment by anukritijha246** [comment]
Checked !

**Pull request merged**
